# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - main

pool:
  vmImage: ubuntu-latest

variables:
 appName: 'Mobile-Frontend-appservice'
 packageDir: 'frontend'

steps:
- task: NodeTool@0
  inputs: 
    versionSpec: '18.x'
  displayName: 'InstallNode.js'


- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    cd ${packageDir}
    npm install
    npm run build
  displayName: 'Build react app'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-mobile-connection'
    appType: 'webAppLinux'
    appName: '$(appName)'
    package: '$(packageDir)/build'
  displayName: 'Deploy to Azure App Service'
